import { useState } from "react";
import UploadCSV from "./UploadCSV";
import CourseOffering from "./CourseOffering";
import TimeTable from "./TimeTable";
import "../../CSS/Home.css";
const Home = ({ courses }) => {
  const [sections, setSections] = useState([
    {
      id: 1142,
      campus: "Byblos",
      numOfStudents: 21,
      numOfSections: 1,
      course: 43,
      capacity: 40,
    },
    {
      id: 1143,
      campus: "Beirut",
      numOfStudents: 31,
      numOfSections: 1,
      course: 43,
      capacity: 40,
    },
    {
      id: 1144,
      campus: "Byblos",
      numOfStudents: 31,
      numOfSections: 1,
      course: 44,
      capacity: 40,
    },
    {
      id: 1145,
      campus: "Beirut",
      numOfStudents: 51,
      numOfSections: 1,
      course: 44,
      capacity: 40,
    },
    {
      id: 1146,
      campus: "Beirut",
      numOfStudents: 181,
      numOfSections: 4,
      course: 45,
      capacity: 40,
    },
    {
      id: 1147,
      campus: "Byblos",
      numOfStudents: 48,
      numOfSections: 1,
      course: 45,
      capacity: 40,
    },
    {
      id: 1148,
      campus: "Byblos",
      numOfStudents: 19,
      numOfSections: 1,
      course: 46,
      capacity: 40,
    },
    {
      id: 1149,
      campus: "Beirut",
      numOfStudents: 46,
      numOfSections: 1,
      course: 46,
      capacity: 40,
    },
    {
      id: 1150,
      campus: "Byblos",
      numOfStudents: 26,
      numOfSections: 1,
      course: 47,
      capacity: 40,
    },
    {
      id: 1151,
      campus: "Beirut",
      numOfStudents: 52,
      numOfSections: 1,
      course: 47,
      capacity: 40,
    },
    {
      id: 1152,
      campus: "Beirut",
      numOfStudents: 170,
      numOfSections: 4,
      course: 48,
      capacity: 40,
    },
    {
      id: 1153,
      campus: "Byblos",
      numOfStudents: 60,
      numOfSections: 1,
      course: 48,
      capacity: 40,
    },
    {
      id: 1154,
      campus: "Beirut",
      numOfStudents: 176,
      numOfSections: 4,
      course: 49,
      capacity: 40,
    },
    {
      id: 1155,
      campus: "Byblos",
      numOfStudents: 47,
      numOfSections: 1,
      course: 49,
      capacity: 40,
    },
    {
      id: 1156,
      campus: "Beirut",
      numOfStudents: 152,
      numOfSections: 3,
      course: 50,
      capacity: 40,
    },
    {
      id: 1157,
      campus: "Byblos",
      numOfStudents: 29,
      numOfSections: 1,
      course: 50,
      capacity: 40,
    },
    {
      id: 1158,
      campus: "Beirut",
      numOfStudents: 82,
      numOfSections: 2,
      course: 51,
      capacity: 40,
    },
    {
      id: 1159,
      campus: "Byblos",
      numOfStudents: 6,
      numOfSections: 1,
      course: 51,
      capacity: 40,
    },
    {
      id: 1160,
      campus: "Beirut",
      numOfStudents: 279,
      numOfSections: 6,
      course: 53,
      capacity: 40,
    },
    {
      id: 1161,
      campus: "Byblos",
      numOfStudents: 62,
      numOfSections: 1,
      course: 53,
      capacity: 40,
    },
    {
      id: 1162,
      campus: "Beirut",
      numOfStudents: 229,
      numOfSections: 5,
      course: 54,
      capacity: 40,
    },
    {
      id: 1163,
      campus: "Byblos",
      numOfStudents: 59,
      numOfSections: 1,
      course: 54,
      capacity: 40,
    },
    {
      id: 1164,
      campus: "Beirut",
      numOfStudents: 6,
      numOfSections: 1,
      course: 69,
      capacity: 40,
    },
    {
      id: 1165,
      campus: "Byblos",
      numOfStudents: 1,
      numOfSections: 1,
      course: 69,
      capacity: 40,
    },
    {
      id: 1166,
      campus: "Beirut",
      numOfStudents: 214,
      numOfSections: 5,
      course: 70,
      capacity: 40,
    },
    {
      id: 1167,
      campus: "Byblos",
      numOfStudents: 70,
      numOfSections: 1,
      course: 70,
      capacity: 40,
    },
    {
      id: 1168,
      campus: "Beirut",
      numOfStudents: 37,
      numOfSections: 1,
      course: 75,
      capacity: 40,
    },
    {
      id: 1169,
      campus: "Byblos",
      numOfStudents: 11,
      numOfSections: 1,
      course: 75,
      capacity: 40,
    },
    {
      id: 1170,
      campus: "Beirut",
      numOfStudents: 12,
      numOfSections: 1,
      course: 76,
      capacity: 40,
    },
    {
      id: 1171,
      campus: "Byblos",
      numOfStudents: 5,
      numOfSections: 1,
      course: 76,
      capacity: 40,
    },
    {
      id: 1172,
      campus: "Beirut",
      numOfStudents: 223,
      numOfSections: 5,
      course: 77,
      capacity: 40,
    },
    {
      id: 1173,
      campus: "Byblos",
      numOfStudents: 84,
      numOfSections: 2,
      course: 77,
      capacity: 40,
    },
    {
      id: 1174,
      campus: "Beirut",
      numOfStudents: 48,
      numOfSections: 1,
      course: 79,
      capacity: 40,
    },
    {
      id: 1175,
      campus: "Byblos",
      numOfStudents: 21,
      numOfSections: 1,
      course: 79,
      capacity: 40,
    },
    {
      id: 1176,
      campus: "Beirut",
      numOfStudents: 9,
      numOfSections: 1,
      course: 80,
      capacity: 40,
    },
    {
      id: 1177,
      campus: "Byblos",
      numOfStudents: 2,
      numOfSections: 1,
      course: 80,
      capacity: 40,
    },
    {
      id: 1178,
      campus: "Beirut",
      numOfStudents: 52,
      numOfSections: 1,
      course: 81,
      capacity: 40,
    },
    {
      id: 1179,
      campus: "Byblos",
      numOfStudents: 21,
      numOfSections: 1,
      course: 81,
      capacity: 40,
    },
    {
      id: 1180,
      campus: "Byblos",
      numOfStudents: 14,
      numOfSections: 1,
      course: 82,
      capacity: 40,
    },
    {
      id: 1181,
      campus: "Beirut",
      numOfStudents: 9,
      numOfSections: 1,
      course: 82,
      capacity: 40,
    },
    {
      id: 1182,
      campus: "Beirut",
      numOfStudents: 30,
      numOfSections: 1,
      course: 83,
      capacity: 40,
    },
    {
      id: 1183,
      campus: "Byblos",
      numOfStudents: 5,
      numOfSections: 1,
      course: 83,
      capacity: 40,
    },
    {
      id: 1184,
      campus: "Beirut",
      numOfStudents: 29,
      numOfSections: 1,
      course: 84,
      capacity: 40,
    },
    {
      id: 1185,
      campus: "Byblos",
      numOfStudents: 11,
      numOfSections: 1,
      course: 84,
      capacity: 40,
    },
    {
      id: 1186,
      campus: "Beirut",
      numOfStudents: 18,
      numOfSections: 1,
      course: 85,
      capacity: 40,
    },
    {
      id: 1187,
      campus: "Byblos",
      numOfStudents: 7,
      numOfSections: 1,
      course: 85,
      capacity: 40,
    },
    {
      id: 1188,
      campus: "Byblos",
      numOfStudents: 24,
      numOfSections: 1,
      course: 90,
      capacity: 40,
    },
    {
      id: 1189,
      campus: "Beirut",
      numOfStudents: 50,
      numOfSections: 1,
      course: 90,
      capacity: 40,
    },
    {
      id: 1190,
      campus: "Byblos",
      numOfStudents: 139,
      numOfSections: 3,
      course: 95,
      capacity: 40,
    },
    {
      id: 1191,
      campus: "Beirut",
      numOfStudents: 412,
      numOfSections: 10,
      course: 95,
      capacity: 40,
    },
    {
      id: 1192,
      campus: "Beirut",
      numOfStudents: 149,
      numOfSections: 3,
      course: 96,
      capacity: 40,
    },
    {
      id: 1193,
      campus: "Byblos",
      numOfStudents: 46,
      numOfSections: 1,
      course: 96,
      capacity: 40,
    },
    {
      id: 1194,
      campus: "Beirut",
      numOfStudents: 3,
      numOfSections: 1,
      course: 101,
      capacity: 40,
    },
    {
      id: 1195,
      campus: "Byblos",
      numOfStudents: 1,
      numOfSections: 1,
      course: 101,
      capacity: 40,
    },
    {
      id: 1196,
      campus: "Beirut",
      numOfStudents: 19,
      numOfSections: 1,
      course: 103,
      capacity: 40,
    },
    {
      id: 1197,
      campus: "Byblos",
      numOfStudents: 2,
      numOfSections: 1,
      course: 103,
      capacity: 40,
    },
    {
      id: 1198,
      campus: "Beirut",
      numOfStudents: 8,
      numOfSections: 1,
      course: 105,
      capacity: 40,
    },
    {
      id: 1199,
      campus: "Byblos",
      numOfStudents: 1,
      numOfSections: 1,
      course: 105,
      capacity: 40,
    },
    {
      id: 1200,
      campus: "Beirut",
      numOfStudents: 2,
      numOfSections: 1,
      course: 106,
      capacity: 40,
    },
    {
      id: 1201,
      campus: "Beirut",
      numOfStudents: 2,
      numOfSections: 1,
      course: 108,
      capacity: 40,
    },
    {
      id: 1202,
      campus: "Beirut",
      numOfStudents: 10,
      numOfSections: 1,
      course: 109,
      capacity: 40,
    },
    {
      id: 1203,
      campus: "Beirut",
      numOfStudents: 8,
      numOfSections: 1,
      course: 110,
      capacity: 40,
    },
    {
      id: 1204,
      campus: "Beirut",
      numOfStudents: 64,
      numOfSections: 1,
      course: 133,
      capacity: 40,
    },
    {
      id: 1205,
      campus: "Byblos",
      numOfStudents: 28,
      numOfSections: 1,
      course: 133,
      capacity: 40,
    },
  ]);
  //if true shows upload Exel, else shows CourseOffering
  const [activeOffering, setActiveOffering] = useState(true);
  return (
    <div>
      <CourseOffering
        active={activeOffering}
        setActive={setActiveOffering}
        sections={sections}
        setSections={setSections}
        courses={courses}
      />
      <UploadCSV
        active={activeOffering}
        setActive={setActiveOffering}
        sections={sections}
        setSections={setSections}
      />
    </div>
  );
};

export default Home;
