# Generated by Django 4.1.3 on 2023-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isChaiperson',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('courseNumber', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('creditsNumber', models.IntegerField()),
                ('campus', models.IntegerField(max_length=1)),
                ('corequisites', models.ManyToManyField(blank=True, to='backend.course')),
                ('prerequisites', models.ManyToManyField(blank=True, to='backend.course')),
            ],
        ),
    ]
