# Generated by Django 4.1.3 on 2023-03-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_ischaiperson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'courseNumber')},
        ),
        migrations.CreateModel(
            name='CourseRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrerequisite', models.BooleanField()),
                ('mainCourse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainCourse', to='backend.course')),
                ('secondCourse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondCourse', to='backend.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='corequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
