# Generated by Django 4.1.3 on 2023-03-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_course_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRelationShip',
        ),
    ]
