# Generated by Django 4.1.3 on 2023-03-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_course_unique_together_courserelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserelationship',
            old_name='mainCourse_id',
            new_name='mainCourse',
        ),
        migrations.RenameField(
            model_name='courserelationship',
            old_name='secondCourse_id',
            new_name='secondCourse',
        ),
    ]
