# Generated by Django 4.1.3 on 2023-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_maincourse_id_courserelationship_maincourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takenCredits', models.IntegerField()),
                ('remainingCredits', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, to='backend.course')),
            ],
        ),
    ]
