# Generated by Django 4.1.3 on 2023-03-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='campus',
        ),
    ]
