# Generated by Django 4.1.3 on 2023-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(default='Byblos', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='BS in Computer Science', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='majors', to='backend.course')),
            ],
        ),
    ]
