# Generated by Django 4.1.3 on 2023-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_student_campus_student_major_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='majors', to='backend.course'),
        ),
    ]
