# Generated by Django 4.1.3 on 2023-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_major_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
