# Generated by Django 4.1.3 on 2023-05-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_major_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takenCredits', models.IntegerField()),
                ('remainingCredits', models.IntegerField()),
                ('campus', models.CharField(max_length=6)),
                ('courses', models.ManyToManyField(blank=True, to='backend.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.major')),
            ],
        ),
    ]
