# Generated by Django 4.1.3 on 2023-05-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='substitutes',
            field=models.ManyToManyField(blank=True, to='backend.course'),
        ),
    ]
