# Generated by Django 4.1.3 on 2023-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_course_substitutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
    ]
