# Generated by Django 4.1.3 on 2023-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_availability_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(max_length=1),
        ),
    ]
