# Generated by Django 4.1.3 on 2023-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='backend.availability'),
        ),
    ]
