# Generated by Django 4.1.3 on 2023-05-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_doctor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='backend.course'),
        ),
    ]
