# Generated by Django 4.1.3 on 2023-05-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_doctor_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='day',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='start_time',
            new_name='start',
        ),
    ]
