# Generated by Django 4.1.3 on 2023-05-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_day_availability_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
