# Generated by Django 4.1.3 on 2023-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_availability_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstYear', models.ManyToManyField(blank=True, related_name='firstYearCourses', to='backend.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.major')),
                ('secondYear', models.ManyToManyField(blank=True, related_name='secondYearCourses', to='backend.course')),
                ('thirdYear', models.ManyToManyField(blank=True, related_name='thirdYearCourses', to='backend.course')),
            ],
        ),
    ]
