# Generated by Django 4.1.3 on 2023-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_studyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='campus',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
